name: AnomalyCableDetection
channels:
  - conda-forge
  - defaults
dependencies:
  - pip:
    - cycler==0.10.0
    - joblib==1.0.1
    - kiwisolver==1.3.1
    - matplotlib==3.4.2
    - numpy==1.20.3
    - pandas==1.2.4
    - patsy==0.5.1
    - pillow==8.2.0
    - pytz==2021.1
    - scikit-learn==0.24.2
    - scipy==1.6.3
    - seaborn==0.11.1
    - sklearn==0.0
    - statsmodels==0.12.2
    - threadpoolctl==2.1.0
